### ISSUE TITLE
    connection closed before message completed

### ISSUE THREAD

**Issue by GeorgeLyu6** [hack-ink/atomicalsir#44]
日志如下，打得太快了，reveal时，本地节点没连通，也没有重试，导致比特币被卡在了中间地址。有没有办法救回来？或者说这个有没有自动重试的机制？
```
        TxOut {
            value: Amount(0.00003431 BTC),
            script_pubkey: Script(OP_PUSHNUM_1 OP_PUSHBYTES_32 de595f4b3a42e2d85887d758a32a226f02dc13dc06ec52ccb07d23409263b958),
        },
    ],
}
2024-01-17T18:22:44.462608Z DEBUG atomicalsir::electrumx: {"success":true,"response":"000000c37d5abeb9e31c6862dc903522c40754b25fdb96369ba61bff6412c3d9"}
2024-01-17T18:22:44.512496Z DEBUG atomicalsir::electrumx: {"success":true,"response":[]}
2024-01-17T18:22:44.512515Z  INFO atomicalsir::electrumx: waiting for UTXO...
Error: error sending request for url (http://172.22.223.180:8080/proxy/blockchain.scripthash.listunspent): connection closed before message completed

Caused by:
    connection closed before message completed
```
```[tasklist]
### Tasks
- [ ] Print hex tx.
- [ ] Cache failed tx to file.
- [ ] If the broadcast fails, retry `x` times.
```

**Comment by AurevoirXavier** [comment]
Currently, there isn't a retry mechanism.

If you have the full log it's possible to recover the BTC.

I'll implement caching and a retry mechanism in version 0.2.0.

**Comment by stringStar** [comment]
Has 0.2.0 been released yet? I didn't see this tag

**Comment by AurevoirXavier** [comment]
> Has 0.2.0 been released yet? I didn't see this tag

I hope to release it this weekend.
